/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liqy_cmakeapp_Jni */

#ifndef _Included_com_liqy_cmakeapp_Jni
#define _Included_com_liqy_cmakeapp_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liqy_cmakeapp_Jni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liqy_cmakeapp_Jni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_liqy_cmakeapp_Jni
 * Method:    stringToJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liqy_cmakeapp_Jni_stringToJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
